---
- name: test-playbook | Test sftp-server role
  hosts: phantom
  become: true
  become_method: sudo
#  become_user: thulana
  vars:
    - sftp_users:
      - name: peter
        password: "$1$salty$li5TXAa2G6oxHTDkqx3Dz/" # passpass
        shell: False
        sftp_directories:
        - directory_only_for_peter1
  roles:
    - sftp_config